image:
  tag: "2.13.3"

timezone: Europe/Berlin

main:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi

worker:
  enabled: false

webhook:
  enabled: false

database:
  type: postgresdb
  postgresdb:
    host: postgres-fb04e5ee-2c80-4773-94bf-47d64c10dee7.c24srvdukvjo.us-east-1.rds.amazonaws.com
    port: 1470
    database: RKsHRzqemrfx
    schema: n8n_it
  passwordSecret:
    existingSecret: n8n-db-password
    existingSecretKey: password

queueMode:
  enabled: true
  redis:
    host: redis-it-master
    port: 6379

n8n:
  host: ITservices.c-5e397ae.kyma.ondemand.com
  protocol: https

secretRefs:
  existingSecret: n8n-it-core-secret