image:
  tag: "2.13.3"

timezone: Europe/Berlin

main:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi

worker:
  enabled: false

webhook:
  enabled: false

database:
  type: postgresdb
  host: postgres-0c548fc8-fc4a-4fbe-adfe-6f12e1795f34.c24srvdukvjo.us-east-1.rds.amazonaws.com
  port: 1470
  database: FYkYoolAgeWd
  user: 074d01b045cd
  schema: n8n_sales
  passwordSecret:
    name: n8n-db-password
    key: password

redis:
  host: redis-sales-master
  port: 6379

n8n:
  host: sales.c-5e397ae.kyma.ondemand.com
  protocol: https

secretRefs:
  existingSecret: n8n-sales-core-secret