architecture: standalone

auth:
  enabled: false

image:
  registry: europe-docker.pkg.dev/kyma-project/prod/external
  repository: bitnami/redis
  tag: "7.0.15-debian-11-r0"
  pullPolicy: IfNotPresent

master:
  persistence:
    enabled: false
