apiVersion: v1
kind: Secret
metadata:
  name: n8n-hr-task-runners
  namespace: sap-n8n-kyma
type: Opaque
stringData:
  N8N_RUNNERS_AUTH_TOKEN: "b7c9f4e8a1d23c6f9e5b7a2c4d8f1e0b6c3d9a7e5f2c1b8a4d6e9f0c3b2a7d1"