apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-hr-task-runner-config
  namespace: sap-n8n-kyma
data:
  n8n-task-runners.json: |
    {
      "python": {
        "allowedStdlibModules": ["datetime"],
        "allowedExternalModules": ["pandas", "openpyxl", "pptx"]
      }
    }