apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-hr
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/n8n-io/n8n-hosting.git
      targetRevision: v1.1.0
      path: charts/n8n
      helm:
        releaseName: n8n-hr
        valueFiles:
          - $values/sap-n8n-gitops/helm-values/n8n/hr-values.yaml
    - repoURL: https://github.com/fakhry000/sap-n8n-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: sap-n8n-kyma
  syncPolicy:
    automated:
      prune: true
      selfHeal: true