apiVersion: v1
kind: Secret
metadata:
  name: redis-hr-secret
  namespace: sap-n8n-kyma
type: Opaque
stringData:
  REDIS_PASSWORD: "RedisHrDemo123!"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-hr
  namespace: sap-n8n-kyma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-hr
  template:
    metadata:
      labels:
        app: redis-hr
    spec:
      containers:
        - name: redis
          image: redis:7.2.13
          ports:
            - containerPort: 6379
          command:
            - redis-server
          args:
            - --requirepass
            - $(REDIS_PASSWORD)
            - --appendonly
            - "no"
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-hr-secret
                  key: REDIS_PASSWORD
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: redis-hr
  namespace: sap-n8n-kyma
spec:
  selector:
    app: redis-hr
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
